language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: htMb3++Rv9iPHYVfEywmSbk7aISYt6XcG6A9GwuXZBGlcPNXwiTJCdTpZvKKgdaG0sDxN9qibMtNMOot0QQTDUMFM3VOjleRohaFV2nKlmhasc+nTM3XSzV5cddkzc1Ky7fB9zeiS965EE4p/sx1bw0AsYD7PG8cFjK4ebWpSd8=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Ms35ExxifbyqfSbPhDFI48lLhElj+gH5axk/83kfTnWvFxKoH6aF1g8FFDCSDiWc7MSnNLnDdNDiEFW/D0ulwpkTFu92XrL7+i1xC31Kc8CelZrTbhyvulsVmMM6z/wfToGRtNMi08/QPRY9P1Ep7NwARvff7qy92bkwCAfvwrc=
sudo: false
