language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: kHlZH60AVhF4coXMARX2UpdXb3v31QgAxMUc7YSI4mztfWBdCrG4RX/taQi205qSwg2Ga0PKsv2/DWqBJD2ODwTEzZiS/PzaC0mf0j52zK6g53UowKCqSMY7fjd3SGpecOpRgML/5p2xQHDxRFEQo59R6QxoTOie9yp4p1ymp6Q=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: Ms35ExxifbyqfSbPhDFI48lLhElj+gH5axk/83kfTnWvFxKoH6aF1g8FFDCSDiWc7MSnNLnDdNDiEFW/D0ulwpkTFu92XrL7+i1xC31Kc8CelZrTbhyvulsVmMM6z/wfToGRtNMi08/QPRY9P1Ep7NwARvff7qy92bkwCAfvwrc=
sudo: false
